### PR TITLE
fix: Detect invalid ICC profile tags

### LINKED ISSUE #4551: [BUG]Segmentation-violation bug at src/include/OpenImageIO/string_view.h:262 in openimageio
### Description

Dear developers, 

We discovered a Segmentation-violation bug in src/include/OpenImageIO/string_view.h:262 while fuzzing iconvert.

The latest version also has this vulnerability.

### Version

```shell
# ./bin/oiiotool --version
3.1.0.0dev

# ./bin/iconvert -v
iconvert: Must have both an input and output filename specified.
iconvert -- copy images with format conversions and other alterations
OpenImageIO 3.1.0.0dev http://www.openimageio.org
```

### PoC

poc2iconvert: https://github.com/Frank-Z7/z-vulnerabilitys/blob/main/poc2iconvert

### Reproduction

```shell
git clone https://github.com/AcademySoftwareFoundation/OpenImageIO.git openimageio
cd openimageio
mkdir build1
cd build1
CFLAGS="-g3 -fsanitize=address -O0 -fno-omit-frame-pointer" CXXFLAGS="-g3 -fsanitize=address -O0 -fno-omit-frame-pointer" LDFLAGS="-fsanitize=address" cmake .. -DCMAKE_CXX_STANDARD=17 -DOpenImageIO_BUILD_MISSING_DEPS=all
make -j20

./bin/iconvert -g 0.7 --separate --rotccw poc2iconvert tmp.png
```

### Address Sanitizer log

```
=================================================================
==659943==ERROR: AddressSanitizer: SEGV on unknown address 0x61f100014fbc (pc 0x7f26e1af481e bp 0x7fff7fa986f0 sp 0x7fff7fa97e68 T0)
==659943==The signal is caused by a READ memory access.
    #0 0x7f26e1af481e  (/lib/x86_64-linux-gnu/libc.so.6+0x1ae81e)
    #1 0x7f26e5fce2e9 in MemcmpInterceptorCommon(void*, int (*)(void const*, void const*, unsigned long), void const*, void const*, unsigned long) ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:881
    #2 0x7f26e5fcebc6 in __interceptor_memcmp ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:892
    #3 0x7f26e5fcebc6 in __interceptor_memcmp ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:887
    #4 0x7f26e31f346d in std::char_traits<char>::compare(char const*, char const*, unsigned long) /usr/include/c++/11/bits/char_traits.h:389
    #5 0x7f26e31f346d in OpenImageIO_v3_1_0::basic_string_view<char, std::char_traits<char> >::compare(OpenImageIO_v3_1_0::basic_string_view<char, std::char_traits<char> >) const /openimageio/src/include/OpenImageIO/string_view.h:262
    #6 0x7f26e31f346d in OpenImageIO_v3_1_0::operator==(OpenImageIO_v3_1_0::basic_string_view<char, std::char_traits<char> >, OpenImageIO_v3_1_0::basic_string_view<char, std::char_traits<char> >) /openimageio/src/include/OpenImageIO/string_view.h:393
    #7 0x7f26e31f346d in OpenImageIO_v3_1_0::decode_icc_profile(OpenImageIO_v3_1_0::span<unsigned char const, 18446744073709551615ul>, OpenImageIO_v3_1_0::ImageSpec&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) /openimageio/src/libOpenImageIO/icc.cpp:319
    #8 0x7f26e38fa7eb in OpenImageIO_v3_1_0::JpgInput::read_icc_profile(jpeg_decompress_struct*, OpenImageIO_v3_1_0::ImageSpec&) /openimageio/src/jpeg.imageio/jpeginput.cpp:438
    #9 0x7f26e3902fd3 in OpenImageIO_v3_1_0::JpgInput::open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, OpenImageIO_v3_1_0::ImageSpec&) /openimageio/src/jpeg.imageio/jpeginput.cpp:363
    #10 0x7f26e390744c in OpenImageIO_v3_1_0::JpgInput::open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, OpenImageIO_v3_1_0::ImageSpec&, OpenImageIO_v3_1_0::ImageSpec const&) /openimageio/src/jpeg.imageio/jpeginput.cpp:162
    #11 0x7f26e3403740 in OpenImageIO_v3_1_0::ImageInput::create(OpenImageIO_v3_1_0::basic_string_view<char, std::char_traits<char> >, bool, OpenImageIO_v3_1_0::ImageSpec const*, OpenImageIO_v3_1_0::Filesystem::IOProxy*, OpenImageIO_v3_1_0::basic_string_view<char, std::char_traits<char> >) /openimageio/src/libOpenImageIO/imageioplugin.cpp:746
    #12 0x7f26e337f1d4 in OpenImageIO_v3_1_0::ImageInput::open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, OpenImageIO_v3_1_0::ImageSpec const*, OpenImageIO_v3_1_0::Filesystem::IOProxy*) /openimageio/src/libOpenImageIO/imageinput.cpp:154
    #13 0x5572d54cb97e in convert_file /openimageio/src/iconvert/iconvert.cpp:333
    #14 0x5572d54ba80d in main /openimageio/src/iconvert/iconvert.cpp:525
    #15 0x7f26e196fd8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #16 0x7f26e196fe3f in __libc_start_main_impl ../csu/libc-start.c:392
    #17 0x5572d54bb4b4 in _start (/openimageio/build1/bin/iconvert+0xc4b4)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/lib/x86_64-linux-gnu/libc.so.6+0x1ae81e)
==659943==ABORTING
```

### Environment

```
ubuntu:22.04
gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04)
clang version 14.0.0-1ubuntu1.1
afl-fuzz++4.22a
```

*Thanks* *for* *your* *time*!

### PR DESCRIPTION
**Pull request by lgritz**
Affects jpeg, tiff, and other formats with embedded ICC profiles. Corrupted/invalid tag offset and/or length values were causing us to touch memory outside the memory allocated for the profile.

Fixes #4551

Not sure if this is wise or not, but for JPEGs, I also enabled some previously commented-out code that has the effect of treating a file with a verifiably corrupted/nonsensical ICC profile block as a failed file. If people ever complain about this in the future, maybe we'll come back and add some kind of global option that lets the app express how tolerant OIIO readers should be about corruptions in files -- do you assume that the whole file is bogus or malicious upon discovering the first invalidity, or do you press on and hope you can get something else useful from the pixels? Let's be cautious for now.

### CODE REVIEW

**Comment by lgritz** [comment]
Fixes https://github.com/AcademySoftwareFoundation/OpenImageIO/issues/4551

File: src/libOpenImageIO/icc.cpp [hunk 1]
```diff
@@ -309,6 +309,13 @@ decode_icc_profile(cspan<uint8_t> iccdata, ImageSpec& spec, std::string& error)
             return false;
         }
 
+        if (!check_span(iccdata, iccdata.data() + tag.offset,
```
Comment (jessey-git) [inline src/libOpenImageIO/icc.cpp:312]: Should we remove the conditional immediately above this line since I think it's duplicated by the stronger `check_span` now?

File: src/jpeg.imageio/jpeginput.cpp [hunk 2]
```diff
@@ -437,9 +437,9 @@ JpgInput::read_icc_profile(j_decompress_ptr cinfo, ImageSpec& spec)
     std::string errormsg;
     bool ok = decode_icc_profile(icc_buf, spec, errormsg);
     if (!ok) {
-        // errorfmt("Could not decode ICC profile: {}\n", errormsg);
-        // return false;
-        // Nah, just skip an ICC specific error?
+        errorfmt("Possible corrupt file, could not decode ICC profile: {}\n",
+                 errormsg);
+        return false;
```
Comment (jessey-git) [inline src/jpeg.imageio/jpeginput.cpp:442]: Initially I was a bit concerned that this would prevent loading of the jpeg itself as you alluded to, however, it looks like the reader here doesn't care about the return value of this function, so I think the image will still be read but would be up to the discretion of the original caller to see if they care about the error status being set or not... It's a bit risky as you say but I don't have a large corpus of jpegs around to know the extent of what might be lurking in terms of folks complaining about it.

**Review by jessey-git — COMMENTED** [review]
Generally looks correct but did have a few comments/questions.

File: src/libOpenImageIO/icc.cpp (hunk 1 above)
Comment (lgritz) [reply src/libOpenImageIO/icc.cpp:312]: Oh, hmmm, I didn't notice that the test was redundant. Sure.

Comment (lgritz) [reply src/libOpenImageIO/icc.cpp:307]: updated

File: src/jpeg.imageio/jpeginput.cpp (hunk 2 above)
Comment (lgritz) [reply src/jpeg.imageio/jpeginput.cpp:442]: Yeah, I honestly don't know the right balance between trying to muddle through reading files that are partially broken, versus being more security-conservative and stopping as soon as something is clearly invalid in the file.

Perhaaps the right thing thing (in the long run, not in this PR) is to add a global attribute about whether/how much to be strict about abandoning reads of files that have anything invalid in them.

**Review by jessey-git — APPROVED** [review]
Seems alright now.
